const UNMATCHED = 'UNMATCHED'
const IN_LOBBY = 'IN_LOBBY'
const IN_GAME = 'IN_GAME'
const GAME_WIN = 'GAME_WIN'
const GAME_FULL = 'GAME_FULL'
const ROLE_OFFICER = 'ROLE_OFFICER'
const ROLE_BACK_OFFICE = 'ROLE_BACK_OFFICE'
const ROLE_DISPATCHER = 'ROLE_DISPATCHER'
const ROLE_WITNESS = 'ROLE_WITNESS'
const MOVE_EVENT = 'MOVE_EVENT'
const HANDLE_MOVE_EVENT = 'HANDLE_MOVE_EVENT'
const HANDLE_GAME_WIN = 'HANDLE_GAME_WIN'

module.exports = {
  UNMATCHED,
  IN_LOBBY,
  IN_GAME,
  GAME_WIN,
  GAME_FULL,
  ROLE_OFFICER,
  ROLE_BACK_OFFICE,
  ROLE_DISPATCHER,
  ROLE_WITNESS,
  MOVE_EVENT,
  HANDLE_MOVE_EVENT,
  HANDLE_GAME_WIN,
}