const UNMATCHED = 'UNMATCHED'
const IN_LOBBY = 'IN_LOBBY'
const IN_GAME = 'IN_GAME'
const GAME_WIN = 'GAME_WIN'
const ROLE_OFFICER = 'ROLE_OFFICER'
const ROLE_BACK_OFFICE = 'ROLE_BACK_OFFICE'
const ROLE_DISPATCHER = 'ROLE_DISPATCHER'
const ROLE_WITNESS = 'ROLE_WITNESS'

module.exports = {
  UNMATCHED,
  IN_LOBBY,
  IN_GAME,
  GAME_WIN,
  ROLE_OFFICER,
  ROLE_BACK_OFFICE,
  ROLE_DISPATCHER,
  ROLE_WITNESS
}